#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-cayman
title: Workshop on Algebraic Geometry over complex number field or in positive characteristic
description: Around positivity of tangent sheaves and anti-canonical divisors
# theme: jekyll-theme-cayman

